# INSERT INTO video (youTubeId, title) VALUES
# ('d6ySoD13XFw', 'Git Conflicts'),
# ('wVzJ-c_DBSA', 'Markdown'),
# ('eyMhGVBsO-Q', 'Welcome to Week 2'),
# ('iETVNC0uLqQ', 'Log4J Overview'),
# ('GbKr2of3g20', 'Git Overview'),
# ('mTne97I3MYw', 'Student Repo and Week 2 Act 3 Walkthrough'),
# ('ie4ydeFQTtg', 'Creating your Individual Project in IntelliJ and GitHub (Week 2 Act 4)'),
# ('9po-VRmZ6mQ', 'Adding Java and Test Directories to your Indie Project'),
# ('edGPz776YGs', 'jUnit Overview'),
# ('UPhNsAojaR0', 'jUnit Demo'),
# ('PbOAH5iRzVQ', 'Week 2 Exercise Overview'),
# ('9z7USj0cp_w', 'Debugging in a JSP'),
# ('7aGOCrW3dNQ', 'IntelliJ Plugins - including Javadoc Generator'),
# ('cLtHrMJKfeY', 'IntelliJ Database View'),
# ('ZbwaWZ9b3Tg', 'Maven Overview'),
# ('KuflISsAmpc', 'Week 1 Overview'),
# ('KOL4QNmHCJA', 'Activity 4 IntelliJ Config Walkthrough'),
# ('JCEaIQaCDgs', 'Working With Assignments from GitHub'),
# ('4HzWKwExaeo', 'Activity 5 First Maven Web App Overview'),
# ('HeOpTFmUCQo', 'Activity 6 The Debugger'),
# ('xpVPr3sWMEs', 'Exercise 1 Overview'),
# ('4KGGkytxlZM', 'Welcome'),
# ('LUJ17rugTKs', 'Individual Project Overview'),
# ('TniysHGAKtE', 'Team Project Overview'),
# ('0ZR5adX7EWo', 'Professional Development Activity Overview'),
# ('uSlO4MeyXYM', 'Using Slack in this Course'),
# ('9qSU8kFix5g', 'Course Set-up')
# ;

INSERT INTO video (title, youTubeId) VALUES
('Week 4 Overview', 'PhGyrgTXXhw'),
('DAO Overview', 'EshxpNqFA2s'),
('Hibernate Overview', 'SuENQ5oOZLg'),
('Hibernate Demo Part 1 - Set up and getAllUsers', '1fj5wnyCsnw'),
('Hibernate Demo Part 2 - More Methods and Unit Testing', '5dzHzqSePEo'),
('Hibernate What Can Go Wrong?!?', '7Z_s1Ypt3vk'),
('Hibernate Demo Part 3 - Create, Update, Delete and a Test DB', '2Y2NprIGErQ'),
('Hibernate Demo Part 4 - Logging', 'w8nijUjVI0M'),
('Week 3 Overview', '-_aATCJ1Yq4'),
('Custom Tag Library Overview', 'MyOyT3koyWE'),
('Custom Tag Library Demo - Week 3 Act 1', 'DzYGUn92YfU'),
('Week 2 Exercise ListTest - One Possible Solution', 'WKxut3MYWpY'),
('Week 2 Exercise Inverse Captcha - One Possible Solution', 'fJo2zsRNFz4')
;