INSERT INTO video (youTubeId, title)  VALUES
('0ZR5adX7EWo', 'Professional Development Activity Overview'),
('1fj5wnyCsnw', 'Hibernate Demo Part 1 - Set up and getAllUsers'),
('2Y2NprIGErQ', 'Hibernate Demo Part 3 - Create, Update, Delete and a Test DB'),
('4HzWKwExaeo', 'Activity 5 First Maven Web App Overview'),
('4KGGkytxlZM', 'Welcome'),
('5dzHzqSePEo', 'Hibernate Demo Part 2 - More Methods and Unit Testing'),
('5tca3yR4K7g', 'AWS Part 4: SSH, Tomcat, MySql'),
('7aGOCrW3dNQ', 'IntelliJ Plugins - including Javadoc Generator'),
('7Z_s1Ypt3vk', 'Hibernate What Can Go Wrong?!?'),
('95gd-T4QA74', 'AWS Part 3: Elastic IP'),
('9po-VRmZ6mQ', 'Adding Java and Test Directories to your Indie Project'),
('9z7USj0cp_w', 'Debugging in a JSP'),
('-_aATCJ1Yq4', 'Week 3 Overview'),
('cLtHrMJKfeY', 'IntelliJ Database View'),
('csT0t8ka8sM', 'AWS Part 6: Deploy!'),
('d6ySoD13XFw', 'Git Conflicts'),
('DzYGUn92YfU', 'Custom Tag Library Demo - Week 3 Act 1'),
('EC4NGcWA4UY', 'Act 1 Walkthrough'),
('edGPz776YGs', 'jUnit Overview'),
('EshxpNqFA2s', 'DAO Overview'),
('eyMhGVBsO-Q', 'Welcome to Week 2'),
('EZOFCr8AbX4', 'AWS Part 5: Remote Access to MySql'),
('F5pc8TLs5h8', 'Auth Part 1 - Overview and Set up'),
('FACzs3wKNpI', 'Week 7 Overview'),
('fJo2zsRNFz4', 'Week 2 Exercise Inverse Captcha - One Possible Solution'),
('GbKr2of3g20', 'Git Overview'),
('HeOpTFmUCQo', 'Activity 6 The Debugger'),
('w8nijUjVI0M', 'Hibernate Demo Part 4 - Logging'),
('htPnL3_DPL8', 'Week 4 Exercise Walkthrough'),
('ie4ydeFQTtg', 'Creating your Individual Project in IntelliJ and GitHub (Week 2 Act 4)'),
('iETVNC0uLqQ', 'Log4J Overview'),
('ifMhRK3wLqI', 'Act 2 Walkthrough'),
('j19uBRHDH3w', 'Generic Hibernate Dao'),
('JCEaIQaCDgs', 'Working With Assignments from GitHub'),
('k0-4keXGRtM', 'Act 1 Walkthrough'),
('KOL4QNmHCJA', 'Activity 4 IntelliJ Config Walkthrough'),
('KuflISsAmpc', 'Week 1 Overview'),
('Ld21wS1BY9s', 'REST Web Services Overview'),
('LUJ17rugTKs', 'Individual Project Overview'),
('LWI_Xi6encU', 'AWS Part 2: EC2'),
('mTne97I3MYw', 'Student Repo and Week 2 Act 3 Walkthrough'),
('MyOyT3koyWE', 'Custom Tag Library Overview'),
('MZzjIY_dB20', 'Act 3 Walkthrough'),
('nJzBJ4aMPgE', 'Auth Part 2 - Tomcat, JSPs, and XML'),
('nn2Nmnn-9XQ', 'Hibernate One-To-Many Part 1 - Orders Table, Config, Entities, Dao'),
('nQoFhQpbBuk', 'Week 5 Overview'),
('okgs3X28D9U', 'Hibernate One-To-Many Part 3 - Displaying Results on the JSP'),
('PbOAH5iRzVQ', 'Week 2 Exercise Overview'),
('PhGyrgTXXhw', 'Week 4 Overview'),
('PRxuzxu5kjw', 'Week 6 Overview'),
('PWGd_E7Ty8U', 'Act 2 Walkthrough'),
('rizqK91UtQc', 'Week 8 Overview'),
('RRS_NHWejmc', 'Comparing Hibernate Entities with .equals'),
('SuENQ5oOZLg', 'Hibernate Overview'),
('TniysHGAKtE', 'Team Project Overview'),
('uD7bKulczMU', 'Hibernate One-To-Many - What Could Go Wrong?!?'),
('UPhNsAojaR0', 'jUnit Demo'),
('uSlO4MeyXYM', 'Using Slack in this Course'),
('_VPFlFQOXV8', 'Web Services and SOAP Overview'),
('W5Y0Mr-cKjI', 'Act 3 Intro'),
('w8nijUjVI0M', 'Hibernate Demo Part 4 - Logging'),
('WKxut3MYWpY', 'Week 2 Exercise ListTest - One Possible Solution'),
('wUrlJm_WDNI', 'Act 4 Intro and Exercise Intro'),
('wVzJ-c_DBSA', 'Markdown'),
('-XfAT7y2A6s', 'Hibernate One-To-Many Part 2 - Unit Testing'),
('xpVPr3sWMEs', 'Exercise 1 Overview'),
('ZbwaWZ9b3Tg', 'Maven Overview'),
('zsGs7K8zxj0', 'Week 9 Overview');
