-- MySQL Script generated by MySQL Workbench
-- Mon 28 Jan 2019 10:21:56 AM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vidmins
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vidmins
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vidmins` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema vidmins
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vidmins
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vidmins` DEFAULT CHARACTER SET latin1 ;
USE `vidmins` ;

-- -----------------------------------------------------
-- Table `vidmins`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vidmins`.`user` ;

CREATE TABLE IF NOT EXISTS `vidmins`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `enc_pass` VARCHAR(1001) NULL DEFAULT NULL,
  `joinDate` DATETIME NULL DEFAULT NULL,
  `firstName` VARCHAR(100) NULL DEFAULT NULL,
  `lastName` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `organization` VARCHAR(100) NULL DEFAULT NULL,
  `introduction` VARCHAR(1001) NULL DEFAULT NULL,
  `status` VARCHAR(30) NULL DEFAULT NULL,
  `dateOfBirth` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vidmins`.`video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vidmins`.`video` ;

CREATE TABLE IF NOT EXISTS `vidmins`.`video` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `youTubeId` VARCHAR(100) NULL DEFAULT '',
  `addDate` DATETIME NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vidmins`.`note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vidmins`.`note` ;

CREATE TABLE IF NOT EXISTS `vidmins`.`note` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NOT NULL,
  `text` TEXT NULL,
  `start` INT NULL,
  `end` INT NULL,
  `createDatetime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `userId` INT NOT NULL,
  `videoId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_1_idx` (`userId` ASC),
  INDEX `fk_note_video_1_idx` (`videoId` ASC),
  CONSTRAINT `fk_note_user_1`
    FOREIGN KEY (`userId`)
    REFERENCES `vidmins`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_note_video_1`
    FOREIGN KEY (`videoId`)
    REFERENCES `vidmins`.`video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `vidmins` ;

-- -----------------------------------------------------
-- Table `vidmins`.`temporary_keys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vidmins`.`temporary_keys` ;

CREATE TABLE IF NOT EXISTS `vidmins`.`temporary_keys` (
  `userId` INT(11) NOT NULL,
  `keyChars` VARCHAR(1001) NOT NULL,
  `timeout` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userId`, `keyChars`),
  CONSTRAINT `fk_temporary_keys_1`
    FOREIGN KEY (`userId`)
    REFERENCES `vidmins`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vidmins`.`user_videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vidmins`.`user_videos` ;

CREATE TABLE IF NOT EXISTS `vidmins`.`user_videos` (
  `userId` INT(11) NOT NULL,
  `videoId` INT(11) NOT NULL,
  INDEX `userId` (`userId` ASC),
  INDEX `videoId` (`videoId` ASC),
  CONSTRAINT `user_videos_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `vidmins`.`user` (`id`),
  CONSTRAINT `user_videos_ibfk_2`
    FOREIGN KEY (`videoId`)
    REFERENCES `vidmins`.`video` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
